# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: gio-research.ai # Website name
baseURL: 'https://gio-research.ai/' # Website URL

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes: ['']
  application/yaml:
    suffixes: [yml]
outputFormats:
  headers:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  redirects:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  wowchemycms_config:
    baseName: config
    isPlainText: true
    mediatype: application/yaml
    notAlternative: false
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    codeFences: true
    noHl: true
    lineNumbersInTable: false
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 3
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
sitemap:
  changefreq: weekly
